### ISSUE TITLE
Connexion administration

### ISSUE THREAD

**Issue by mathoumath** [Arwantys/YourHabbo#1]
Salut,

Quand on veut se rendre dans le pannel d'administration en entrant son mot de passe rien ne s'exécute (même en ayant créé son compte dans la DB) même pas une notification.

J'ai réussi à corriger le soucis de la notification en corrigeant l'url:  " /core/action/action?to=admlogin " par " /core/action/action.php?to=admlogin " juste en ajoutant l'extension.

Côté administration impossible de répondre à un ticket, même soucis manque le " .php" avant le " ? " non résolu de mon côte je n'arrive pas à trouver le fichier.

**Comment by mathoumath** [comment]
Bonjour,

Je vous ai répondu sur le forum avec les accès du compte pour essayer de votre côté

**Comment by Arwantys** [comment]
J'ai mis à jour le fichier .htaccess, essayez avec le nouveau.
